### ISSUE TITLE
Words.md почти переведён

### ISSUE THREAD

**Issue by Sbezhik** [NotDotTeam/covid-19#11]
Нужен перевод картинок (The fonts are Open Sans (https://fonts.google.com/specimen/Open+Sans) and Patrick Hand(https://fonts.google.com/specimen/Patrick+Hand))

Если кто-нибудь ещё переведёт весь большой комикс про механизм действия приложения (в статье приведена только сокращённая версия), честь ему и хвала!

**Comment by toby3d** [comment]
Я в процессе перевода текста на всех изображениях #10

**Comment by Sbezhik** [comment]
Как дела с картинками-карантинками? Нужна помощь?

> Я в процессе перевода текста на всех изображениях #10

**Comment by Sbezhik** [comment]
Можешь как-то сделать, чтобы плашка с переводами была синхронизированна с оригиналом?

**Comment by toby3d** [comment]
> Как дела с картинками-карантинками? Нужна помощь?

В целом, всё идёт хорошо. Я стараюсь перевести их хорошо сразу, ибо в отличии от текста каждая правка графики будет ухудшать её качество, чего мы не хотим. Немного дольше чем обычно ковыряюсь с комиксом про приложения и формулировками в "брифинге миссии" по входу/выходу в карантин. Но, думаю, на днях-таки солью свои правки.

> Можешь как-то сделать, чтобы плашка с переводами была синхронизированна с оригиналом?

Речь о списке языков?

![image](https://user-images.githubusercontent.com/5412322/81786151-bcf2bd80-9518-11ea-88fc-36a3f3b13ceb.png)

Если да, то надо убедиться, что всё более-менее переведено и после я сделаю соответствующую правку в репозитории Ники.
