### ISSUE TITLE
Что в настоящий момент с переводом? 

### ISSUE THREAD

**Issue by TesloStep** [NotDotTeam/covid-19#15]
Судя по коментариям работа практически завершена, но в публичной версии только половина текста готова.

**Comment by toby3d** [comment]
Вторая половина лежит #14, но в ней многовато конфликтов и лишних изменений, автор не отвечает на запрос об исправлениях. Я последние пару недель был занят работой.

Планирую на этой неделе добить это всё хоть до какого-то более-менее завершённого состояния и запросить добавление ссылки в репозитории Ники.

**Comment by toby3d** [comment]
Ссылка добавлена, теперь всё официально!
